<table>
	<tr>
		<td>suppliername</td>
		<td><?=$suppliername?></td>
	</tr>
	<tr>
		<td>supplieraddress</td>
		<td><?=$supplieraddress?></td>
	</tr>
	<tr>
		<td>linkcode</td>
		<td><?=$linkcode?></td>
	</tr>
	<tr>
		<td>suppliercontactname</td>
		<td><?=$suppliercontactname?></td>
	</tr>
	<tr>
		<td>telephonenumber</td>
		<td><?=$telephonenumber?></td>
	</tr>
	<tr>
		<td>faxnumber</td>
		<td><?=$faxnumber?></td>
	</tr>
	<tr>
		<td>legalentityname</td>
		<td><?=$legalentityname?></td>
	</tr>
	<tr>
		<td>legalentitytype</td>
		<td><?=$legalentitytype?></td>
	</tr>
	<tr>
		<td>regno</td>
		<td><?=$regno?></td>
	</tr>
	<tr>
		<td>regcountry</td>
		<td><?=$regcountry?></td>
	</tr>
	<tr>
		<td>emailaddress</td>
		<td><?=$emailaddress?></td>
	</tr>
	<tr>
		<td>website</td>
		<td><?=$website?></td>
	</tr>
	<tr>
		<td>cellnumber</td>
		<td><?=$cellnumber?></td>
	</tr>
	<tr>
		<td>gpscoord</td>
		<td><?=$gpscoord?></td>
	</tr>
	<tr>
		<td>postaddress</td>
		<td><?=$postaddress?></td>
	</tr>
	<tr>
		<td>province</td>
		<td><?=$province?></td>
	</tr>
	<tr>
		<td>districtmunicipality</td>
		<td><?=$districtmunicipality?></td>
	</tr>
	<tr>
		<td>localmunicipality</td>
		<td><?=$localmunicipality?></td>
	</tr>
	<tr>
		<td>financialperiod</td>
		<td><?=$financialperiod?></td>
	</tr>
	<tr>
		<td>annualturnover</td>
		<td><?=$annualturnover?></td>
	</tr>
	<tr>
		<td>vatnumber</td>
		<td><?=$vatnumber?></td>
	</tr>
	<tr>
		<td>seniormgttitle</td>
		<td><?=$seniormgttitle?></td>
	</tr>
	<tr>
		<td>seniormgtfname</td>
		<td><?=$seniormgtfname?></td>
	</tr>
	<tr>
		<td>seniormgtsname</td>
		<td><?=$seniormgtsname?></td>
	</tr>
	<tr>
		<td>seniormgtcommethod</td>
		<td><?=$seniormgtcommethod?></td>
	</tr>
	<tr>
		<td>seniormgtcellnumber</td>
		<td><?=$seniormgtcellnumber?></td>
	</tr>
	<tr>
		<td>seniormgttelnumber</td>
		<td><?=$seniormgttelnumber?></td>
	</tr>
	<tr>
		<td>seniormgtemail</td>
		<td><?=$seniormgtemail?></td>
	</tr>
	<tr>
		<td>salestitle</td>
		<td><?=$salestitle?></td>
	</tr>
	<tr>
		<td>salescommethod</td>
		<td><?=$salescommethod?></td>
	</tr>
	<tr>
		<td>salesfname</td>
		<td><?=$salesfname?></td>
	</tr>
	<tr>
		<td>salessname</td>
		<td><?=$salessname?></td>
	</tr>
	<tr>
		<td>salescellnumber</td>
		<td><?=$salescellnumber?></td>
	</tr>
	<tr>
		<td>salestelnumber</td>
		<td><?=$salestelnumber?></td>
	</tr>
	<tr>
		<td>salesemail</td>
		<td><?=$salesemail?></td>
	</tr>
	<tr>
		<td>admintitle</td>
		<td><?=$admintitle?></td>
	</tr>
	<tr>
		<td>admincommethod</td>
		<td><?=$admincommethod?></td>
	</tr>
	<tr>
		<td>adminfname</td>
		<td><?=$adminfname?></td>
	</tr>
	<tr>
		<td>adminsname</td>
		<td><?=$adminsname?></td>
	</tr>
	<tr>
		<td>admincellnumber</td>
		<td><?=$admincellnumber?></td>
	</tr>
	<tr>
		<td>admintelnumber</td>
		<td><?=$admintelnumber?></td>
	</tr>
	<tr>
		<td>adminemail</td>
		<td><?=$adminemail?></td>
	</tr>
	<tr>
		<td>financetitle</td>
		<td><?=$financetitle?></td>
	</tr>
	<tr>
		<td>financecommethod</td>
		<td><?=$financecommethod?></td>
	</tr>
	<tr>
		<td>financefname</td>
		<td><?=$financefname?></td>
	</tr>
	<tr>
		<td>financesname</td>
		<td><?=$financesname?></td>
	</tr>
	<tr>
		<td>financecellnumber</td>
		<td><?=$financecellnumber?></td>
	</tr>
	<tr>
		<td>financetelnumber</td>
		<td><?=$financetelnumber?></td>
	</tr>
	<tr>
		<td>financeemail</td>
		<td><?=$financeemail?></td>
	</tr>
	<tr>
		<td>supporttitle</td>
		<td><?=$supporttitle?></td>
	</tr>
	<tr>
		<td>supportcommethod</td>
		<td><?=$supportcommethod?></td>
	</tr>
	<tr>
		<td>supportfname</td>
		<td><?=$supportfname?></td>
	</tr>
	<tr>
		<td>supportsname</td>
		<td><?=$supportsname?></td>
	</tr>
	<tr>
		<td>supportcellnumber</td>
		<td><?=$supportcellnumber?></td>
	</tr>
	<tr>
		<td>supporttelnumber</td>
		<td><?=$supporttelnumber?></td>
	</tr>
	<tr>
		<td>supportemail</td>
		<td><?=$supportemail?></td>
	</tr>
	<tr>
		<td>profiletitle</td>
		<td><?=$profiletitle?></td>
	</tr>
	<tr>
		<td>profilecommethod</td>
		<td><?=$profilecommethod?></td>
	</tr>
	<tr>
		<td>profilefname</td>
		<td><?=$profilefname?></td>
	</tr>
	<tr>
		<td>profilesname</td>
		<td><?=$profilesname?></td>
	</tr>
	<tr>
		<td>profilecellnumber</td>
		<td><?=$profilecellnumber?></td>
	</tr>
	<tr>
		<td>profiletelnumber</td>
		<td><?=$profiletelnumber?></td>
	</tr>
	<tr>
		<td>profileemail</td>
		<td><?=$profileemail?></td>
	</tr>
	<tr>
		<td>bankname</td>
		<td><?=$bankname?></td>
	</tr>
	<tr>
		<td>bankaccnumber</td>
		<td><?=$bankaccnumber?></td>
	</tr>
	<tr>
		<td>bankbranchname</td>
		<td><?=$bankbranchname?></td>
	</tr>
	<tr>
		<td>bankbranchcode</td>
		<td><?=$bankbranchcode?></td>
	</tr>
	<tr>
		<td>bankacctype</td>
		<td><?=$bankacctype?></td>
	</tr>
	<tr>
		<td>bankaccholdername</td>
		<td><?=$bankaccholdername?></td>
	</tr>
	<tr>
		<td>businessdscr</td>
		<td><?=$businessdscr?></td>
	</tr>
	<tr>
		<td>businessindustry</td>
		<td><?=$businessindustry?></td>
	</tr>
	<tr>
		<td>businessmarketsegment</td>
		<td><?=$businessmarketsegment?></td>
	</tr>
	<tr>
		<td>beescorecardavail</td>
		<td><?=$beescorecardavail?></td>
	</tr>
	<tr>
		<td>beesscorecardrating</td>
		<td><?=$beesscorecardrating?></td>
	</tr>
	<tr>
		<td>beeexpirydate</td>
		<td><?=$beeexpirydate?></td>
	</tr>
	<tr>
		<td>beedaterated</td>
		<td><?=$beedaterated?></td>
	</tr>
	<tr>
		<td>beeexclusioncode</td>
		<td><?=$beeexclusioncode?></td>
	</tr>
	<tr>
		<td>beeexclusionreason</td>
		<td><?=$beeexclusionreason?></td>
	</tr>
	<tr>
		<td>beeagencyname</td>
		<td><?=$beeagencyname?></td>
	</tr>
	<tr>
		<td>beeagencynumber</td>
		<td><?=$beeagencynumber?></td>
	</tr>
	<tr>
		<td>beescoreownership</td>
		<td><?=$beescoreownership?></td>
	</tr>
	<tr>
		<td>beescoremgt</td>
		<td><?=$beescoremgt?></td>
	</tr>
	<tr>
		<td>beescorequity</td>
		<td><?=$beescorequity?></td>
	</tr>
	<tr>
		<td>beescoreskilldev</td>
		<td><?=$beescoreskilldev?></td>
	</tr>
	<tr>
		<td>beescoreprocurement</td>
		<td><?=$beescoreprocurement?></td>
	</tr>
	<tr>
		<td>beescoreenterprisedev</td>
		<td><?=$beescoreenterprisedev?></td>
	</tr>
	<tr>
		<td>beescoresociodev</td>
		<td><?=$beescoresociodev?></td>
	</tr>
	<tr>
		<td>beescoretotal</td>
		<td><?=$beescoretotal?></td>
	</tr>
	<tr>
		<td>beescoredeemedtotal</td>
		<td><?=$beescoredeemedtotal?></td>
	</tr>
	<tr>
		<td>beescoreprocurementlevel</td>
		<td><?=$beescoreprocurementlevel?></td>
	</tr>
	<tr>
		<td>beescoreenterprisetype</td>
		<td><?=$beescoreenterprisetype?></td>
	</tr>
	<tr>
		<td>beescorevalueadding</td>
		<td><?=$beescorevalueadding?></td>
	</tr>
	<tr>
		<td>beescoreenterprisedevbeneficiary</td>
		<td><?=$beescoreenterprisedevbeneficiary?></td>
	</tr>
	<tr>
		<td>beescoreparastatal</td>
		<td><?=$beescoreparastatal?></td>
	</tr>
	<tr>
		<td>beescoremultinational</td>
		<td><?=$beescoremultinational?></td>
	</tr>
	<tr>
		<td>terms</td>
		<td><?=$terms?></td>
	</tr>
	<tr>
		<td>declaration</td>
		<td><?=$declaration?></td>
	</tr>
	<tr>
		<td>datacomplete</td>
		<td><?=$datacomplete?></td>
	</tr>
	<tr>
		<td>lastfield</td>
		<td><?=$lastfield?></td>
	</tr>
	<tr>
		<td>lasttab</td>
		<td><?=$lasttab?></td>
	</tr>
	<tr>
		<td>shareholders</td>
		<td><?=$shareholders?></td>
	</tr>
	<tr>
		<td>uploads</td>
		<td><?=$uploads?></td>
	</tr>
	<tr>
		<td>businessservices</td>
		<td><?=$businessservices?></td>
	</tr>
</table>
